import { FileText, GraduationCap, Languages, Scissors } from 'lucide-react';
import type { ImportJobStep } from '../api/dashboard.types';

export const LANGUAGES = [
  { code: 'pl', name: 'Polski' },
  { code: 'en', name: 'English' },
  { code: 'es', name: 'Español' },
  { code: 'fr', name: 'Français' },
  { code: 'de', name: 'Deutsch' },
  { code: 'it', name: 'Italiano' },
  { code: 'pt', name: 'Português' },
  { code: 'ru', name: 'Русский' },
  { code: 'uk', name: 'Українська' },
  { code: 'cs', name: 'Čeština' },
  { code: 'sk', name: 'Slovenčina' },
  { code: 'hu', name: 'Magyar' },
  { code: 'ro', name: 'Română' },
  // { code: "bg", name: "Български" },
  // { code: "hr", name: "Hrvatski" },
  // { code: "sr", name: "Српски" },
  { code: 'sl', name: 'Slovenščina' },
  { code: 'lt', name: 'Lietuvių' },
  { code: 'lv', name: 'Latviešu' },
  { code: 'et', name: 'Eesti' },
  { code: 'fi', name: 'Suomi' },
  { code: 'sv', name: 'Svenska' },
  { code: 'da', name: 'Dansk' },
  { code: 'no', name: 'Norsk' },
  { code: 'nl', name: 'Nederlands' },
  // { code: "ja", name: "日本語" },
  // { code: "ko", name: "한국어" },
  // { code: "zh", name: "中文" },
  // { code: "ar", name: "العربية" },
  // { code: "hi", name: "हिन्दी" },
  { code: 'tr', name: 'Türkçe' },
  // { code: "el", name: "Ελληνικά" },
  // { code: "he", name: "עברית" },
  // { code: "th", name: "ไทย" },
  // { code: "vi", name: "Tiếng Việt" },
  // { code: "id", name: "Bahasa Indonesia" },
  // { code: "ms", name: "Bahasa Melayu" },
  // { code: "fa", name: "فارسی" },
];

export const steps = [
  {
    icon: FileText,
    title: 'Pobieramy transkrypcję',
    match: [
      'QUEUED',
      'FETCH_VIDEO_INFO',
      'FETCH_TRANSCRIPT',
    ] as ImportJobStep[],
  },
  {
    icon: Scissors,
    title: 'Dzielimy na zdania',
    match: ['SAVE_VIDEO'] as ImportJobStep[],
  },
  {
    icon: Languages,
    title: 'Tłumaczymy i wyjaśniamy',
    match: ['ENSURE_LANGUAGE'] as ImportJobStep[],
  },
  {
    icon: GraduationCap,
    title: 'Tworzymy materiały do nauki',
    match: ['TOKENIZE_SEGMENTS', 'COMPLETED'] as ImportJobStep[],
  },
];
